services:
  web:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.emgvr.rule=Host(`${DOMAIN}`) && PathPrefix(`/`) || Host(`vr.${DOMAIN}`)"
      - "traefik.http.routers.emgvr.entrypoints=websecure,web"
      - "trafeik.http.routers.emgvr.tls=true"
      - "traefik.http.middlewares.emgvr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.emgvr.middlewares=emgvr-https-redirect"
      - "traefik.http.routers.emgvr.tls.certresolver=production" # May want to try staging before production as production has a rate limit
      - "traefik.http.services.emgvr.loadbalancer.server.port=8000"
    networks:
      - "traefik-proxy"

networks:
  traefik-proxy:
    external: true
